### ISSUE TITLE
no error message for constant predicate with no argument

### ISSUE THREAD

**Issue by happysf128** [aig-upf/2017-planning-with-simulators#3]
Although this is unlikely to happen, but it did take me some time to find what happened. If you have an constant predicate(does not in any action effects) without any arguments, the planner would not able to decode the representation and have a Python TypeError.

**Comment by happysf128** [comment]
By the way, here is the error message that I got


`Traceback (most recent call last):
  File "run.py", line 17, in <module>
    runner.main(sys.argv[1:])
  File "/home/ghu1/Dropbox/fs/python/parser/runner.py", line 244, in main
    return run(parse_arguments(args))
  File "/home/ghu1/Dropbox/fs/python/parser/runner.py", line 234, in run
    representation.generate()
  File "/home/ghu1/Dropbox/fs/python/parser/representation.py", line 41, in generate
    self.serialize_static_extensions()
  File "/home/ghu1/Dropbox/fs/python/parser/representation.py", line 62, in serialize_static_extensions
    serialized = elem.serialize_data(self.index.objects.data)
  File "/home/ghu1/Dropbox/fs/python/parser/static.py", line 138, in serialize_data
    return [serialize_symbol(self.elems[()], symbols)]  # We simply print the only element
  File "/home/ghu1/Dropbox/fs/python/parser/static.py", line 33, in serialize_symbol
    serialized = symbol if python.utils.is_int(symbol) else table[symbol]
  File "/home/ghu1/Dropbox/fs/python/utils.py", line 62, in is_int
    int(s)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
`

**Comment by happysf128** [comment]
Not only constant predicate with no argument. Rephrase it in a new issue.
